# These are supported funding model platforms

github: [Drombler]
custom: ['https://www.paypal.com/donate?token=Fyvl0SK8gRMOuuie1RYyygGLq9wWatzLwFJwQF9S4aUQZEEaGcSQ5Kg9Cn9LQqisE9qni1f8bCvOfy_A', 'https://flattr.com/submit/auto?fid=32jl9p&url=http%3A%2F%2Fwww.drombler.org']
