//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.06 at 09:26:09 PM CEST 
//


package tutorial.extension.foo.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for foos element declaration.
 * * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="foos"&gt;
 *   &lt;complexType&gt;
 *     &lt;complexContent&gt;
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="foo" type="{http://www.drombler.org/schema/acp/status}FooType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/restriction&gt;
 *     &lt;/complexContent&gt;
 *   &lt;/complexType&gt;
 * &lt;/element&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "foo"
})
@XmlRootElement(name = "foos", namespace = "http://www.mycompany.com/schema/myapp/foos")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2019-10-06T09:26:09+02:00", comments = "JAXB RI v2.3.0")
public class FoosType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-10-06T09:26:09+02:00", comments = "JAXB RI v2.3.0")
    protected List<FooType> foo;

    /**
     * Gets the value of the foo property.
       * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is
     * not a <CODE>set</CODE> method for the foo property.
       * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFoo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FooType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-10-06T09:26:09+02:00", comments = "JAXB RI v2.3.0")
    public List<FooType> getFoo() {
        if (foo == null) {
            foo = new ArrayList<FooType>();
        }
        return this.foo;
    }

}
