[[contextFramework]]
= Context Framework
:toc:
:numbered:

The _Context Framework_ allows components such as _Dockable Panes_ and _Actions_ to communicate in a loosly coupled way - even across bundle boundaries.

The basic abstraction is the [org.drombler.commons.context.Context](http://www.drombler.org/DromblerCommons/current/docs/site/apidocs/org/drombler/commons/context/Context.html) interface. You can use it to look for instances of the specified type and listen for changes of its content.

== Content Providers

To add content to a _Context_ you need a mutable _Context_ implementation such as: org.drombler.commons.context.SimpleContext

Typical content providers are:

 * _Editor Dockable Panes_ (the object to edit, custom implementations of _action command interfaces_ such as org.drombler.acp.core.standard.action.Savable to interact with actions such as the "Save" action)
 * _View Dockable Panes_ with a "current selection"

== Content Consumers

Content consumers query a _Context_ for some type and listen for changes in a _Context_ content using a ContextListener.

Typical content consumers are:

 * _View Dockable Panes_ (show some information about an object)
 * _Actions_ (look for instances of their action command interface)

== Active Context

The _Active Context_ provides access to the content of the local _Context_ of the currently active object (in _Drombler FX_: _Dockable Pane_).

Actions and _Dockable Panes_ interested in the _Active Context_ can implement the following interface: org.drombler.commons.context.ActiveContextSensitive

_Drombler FX_ will inject the _Active Context_.

Note: Don't forget to listen for changes in the _Active Context_ content using a ContextListener!

See [GettingStarted] and [ActionsMenusToolbars] for samples.


== Application Context

The _Application-wide Context_ provides access to the combined content of the local _Context_ of all currently open _Dockable Panes_.

Actions and _Dockable Panes_ interested in the _Application-wide Context_ can implement the following interface: org.drombler.commons.context.ApplicationContextSensitive

_Drombler FX_ will inject the _Application Context_.

Note: Don't forget to listen for changes in the _Application Context_ content using a ContextListener!

See [ActionsMenusToolbars] for a sample.
