[[actionsMenusToolbars]]
= Actions, Menus and Toolbars
:toc:
:numbered:

https://www.drombler.org/drombler-commons[Drombler Commons] provides an Action Framework, which keeps the state 
(enabled/ disabled, selected/ unselected etc.), the information (texts, image etc.) and the logic between menu items and
 toolbar buttons in sync. In addition https://www.drombler.org/drombler-acp[Drombler ACP] provides annotations to easily 
register new actions, menus, menu items, toolbars and toolbar buttons.

The rest of this section describes how to use this framework in a _Drombler FX_ application.

== Action Implementations supported by _Drombler FX_

_Drombler FX_ supports 3 ways to implement actions.

=== Implement org.drombler.commons.action.ActionListener;

The easiest way to implement ActionListener is to extend AbstractActionListener:

[source,java]
----
include::{sourcedir}/tutorial/action/Test1Action.java[lines=17..25]
----

*Pros*:

* maximally reusable; GUI toolkit agnostic (no dependencies on _JavaFX_)

*Cons*: 

* dependencies on _Drombler Commons_



Note: For _Drombler FX_ applications, the generic type parameter passed to ActionListener/ AbstractActionListener must be javafx.event.ActionEvent or one of its super-classes (here: Object).
 
=== Implement javafx.event.EventHandler<javafx.event.ActionEvent>

[source,java]
----
include::{sourcedir}/tutorial/action/Test2Action.java[lines=17..26]
----


*Pros*:

* very close to standard _JavaFX_ code
* no dependencies on _Drombler Commons_ (apart from some annotations; see further down)

*Cons*: 

* dependencies on _JavaFX_

=== Implement org.drombler.commons.action.fx.FXAction

FXAction is an extension of javafx.event.EventHandler&lt;javafx.event.ActionEvent&gt;.

The easiest way to implement FXAction is to extend AbstractFXAction:

[source,java]
----
include::{sourcedir}/tutorial/action/Test3Action.java[lines=17..26]
----


*Pros*:

* maximal control

*Cons*: 

* dependencies on _JavaFX_
* dependencies on _Drombler Commons_

== Toggle Action Implementations supported by _Drombler FX_

_Drombler FX_ supports 2 ways to implement toggle actions.

=== Implement org.drombler.commons.action.ToggleActionListener

The easiest way to implement ToggleActionListener is to extend AbstractToggleActionListener:

[source,java]
----
include::{sourcedir}/tutorial/action/Test1ToggleAction.java[lines=17..25]
----

Note: For _Drombler FX_ applications, the generic type parameter passed to ToggleActionListener/ AbstractToggleActionListener must be _javafx.event.ActionEvent_ or one of its super-classes (here: Object).

*Pros*:

* maximally reusable; GUI toolkit agnostic (no dependencies on JavaFX)

*Cons*: 

* dependencies on _Drombler Commons_

=== Implement org.drombler.commons.action.fx.FXToggleAction

FXToggleAction is an extension of FXAction.

The easiest way to implement FXToggleAction is to extend AbstractFXAction:

[source,java]
----
include::{sourcedir}/tutorial/action/Test2ToggleAction.java[lines=17..52]
----

*Pros*:

* maximal control

*Cons*: 

* dependencies on _JavaFX_
* dependencies on _Drombler Commons_
* currently: more code is required


== Registering Actions, Menu Items and Toolbar Buttons

The simplest way to register your actions, menu items and toolbar buttons is to use some annotations on your Action impementation.

=== Register an Action

To register an Action use the @Action annotation:

[source,java]
----
include::{sourcedir}/tutorial/action/AnnotatedAction.java[lines=17..20]
----

[cols="1,10",options="header"]
|===
|Property | Value

|id | used by @MenuEntry and @ToolbarEntry
|category | used to group actions (currently this has not effect, but might be used in future)
|displayName | 
the text to be displayed, e.g. as the text for menu items or the tooltip for toolbar buttons. 
If the value starts with '%' the rest of the value is interpreted as a property key and the value gets looked-up in the 
Bundle.properties file (or a locale specific derivation of this file), which has to be in the same package as the 
annotated action. Note: Maven expects resources to be in the resources directory.
|accelerator | the accelerator to be used for this action
|icon | the icon to be used for this action. Note that this only specifies the name pattern. 
_Drombler FX_ looks for &lt;icon-base-name&gt;16.&lt;icon-extension&gt; for menu items (expected to be 16x16 pixels) and
&lt;icon-base-name&gt;24.&lt;icon-extension&gt; for toolbar buttons (expected to be 24x24 pixels). 
In the example above _Drombler FX_ would look for test116.png and test124.png. Note: Maven expects resources to be in a 
resources directory. If you're using drombler-fx-parent as your parent POM, it's best to put binary files under the 
resources-bin directory as this directory has been configured not to be filtered for variables.
|resourceBundleBaseName|the base name of the ResourceBundle, 'Bundle' (for the package ResourceBundle) or empty (for the class ResourceBundle)
|===
.Action Annotation Properties

Note: If the displayName contains an underscore ('_'), the following character is the mnemonic character of this action.

=== Register a Menu Item

To register a menu item use the @MenuEntry annotation:

[source,java]
----
include::{sourcedir}/tutorial/action/AnnotatedMenuEntry.java[lines=17..19]
----

[cols="1,10",options="header"]
|===
|Property | Value

|actionId | the id of the Action to be registered as a menu item. This property can be omitted, if there is an @Action 
annotation on the same class.
|path | a slash '/' delimited path of menu IDs (see further down)
|position | the position to order the menu items in a menu. It's a best practice to leave out some positions between 
entries to allow other bundles to register entries between some existing ones.
|===

*Separators*: If the positions of two consecutive entries are not in the same thousand group, _Drombler FX_ will add a 
separator between them.

=== Register a Toolbar Button

To register a toolbar button use the @ToolBarEntry annotation:

[source,java]
----
include::{sourcedir}/tutorial/action/AnnotatedToolBarEntry.java[lines=17..19]
----

[cols="1,10",options="header"]
|===
|Property | Value

|actionId | the id of the Action to be registered as a toolbar button. This property can be omitted, if there is an 
@Action annotation on the same class.
|toolBarId | the ID of the toolbar this toolbar button should be registered to (see further down)
|position | the position to order the toolbar buttons in a toolbar. It's a best practice to leave out some positions 
between entries to allow other bundles to register entries between some existing ones.
|===

=== Register a Toggle Action

Toggle Actions need to be registered using the @ToggleAction annotation. The properties are the same as for the 
@Action annotation (see above).


=== Register a Toggle Menu Item

To register a toggle menu item use the @ToggleMenuEntry annotation. The properties are the same as for the @MenuEntry 
annotation (see above), but the actionId must be the ID of a toggle action and there is an additional property:

*toggleGroupId*: if present, only one menu item of the same toggle group can be selected, else any number of menu items 
may be selected.

=== Register a Toggle Toolbar Button

To register a toggle toolbar button use the @ToolBarToggleEntry annotation. The properties are the same as for the 
@ToolBarEntry annotation (see above), but the actionId must be the ID of a toggle action and there is an additional 
property:

*toggleGroupId*: if present, only one toolbar button of the same toggle group can be selected, else any number of 
toolbar buttons may be selected.

[[menus]]
=== Register Menus and Sub-Menus

Menus and sub-menus can be registered using the @Menu annotation on a package (in package-info.java):

[source,java]
----
include::{sourcedir}/tutorial/action/menu/package-info.java[lines=15..19]
----

[cols="1,10",options="header"]
|===
|Property | Value

|id | the ID of the menu to be registered. This ID can be used in the path property of menus and menu items.
|displayName | the text of the menu. If the value starts with '%' the rest of the value is interpreted as a property key
 and the value gets looked-up in the Bundle.properties file (or a locale specific derivation of this file), which has to
 be in the same package. Note: Maven expects resources to be in the resources directory.
|path | a slash '/' delimited path of menu IDs. If it is omitted, then the menu will be registered directly in the menu 
bar.
|position | the position to order the menus in a parent menu/ menu bar. It's a best practice to leave out some positions
 between entries to allow other bundles to register entries between some existing ones. 
|===

Note: If the displayName contains an underscore ('_'), the following character is the mnemonic character of this menu.


[[toolBars]]
=== Register Tool Bars

Tool bars can be registered using the @ToolBar annotation on a package (in package-info.java):

[source,java]
----
include::{sourcedir}/tutorial/action/toolbar/package-info.java[lines=15..19]
----

[cols="1,10",options="header"]
|===
|Property | Value

|id | the ID of the menu to be registered. This ID can be used as the toolBarId property of toolbar buttons.
|displayName | the text of the toggle menu item registered at "View/Toolbars". If the value starts with '%' the rest of 
the value is interpreted as a property key and the value gets looked-up in the Bundle.properties file (or a locale 
specific derivation of this file), which has to be in the same package. Note: Maven expects resources to be in the 
resources directory.
|position | the position to order the toolbars in the toolbar container and in the "View/Toolbars" menu. It's a best 
practice to leave out some positions between entries to allow other bundles to register entries between some existing 
ones. 
|visible | indicates if the toolbar should initially be visible or not. The default is "true". The visibility can be 
toggled in the "View/Toolbars" menu.
|===

Note: If the displayName contains an underscore ('_'), the following character is the mnemonic character of the registered toggle menu item.

Note: For every registered toolbar a toggle menu item will registered at "View/Toolbars".

== The Standard Actions, Menus and Toolbars

As of this writing _Drombler FX_ provides the following standard actions, menus, menu items, toolbars and toolbar buttons:

Menu IDs:

 * *File* (position = 10)
 * *View* (position = 40)
 ** *Toolbars* (position = 5100)
 * *Help* (position = 900)

Toolbar IDs:
 
 * *file* (position = 10)

Actions, Menu Items and Toolbar Buttons:

*Save*:

[source,java]
----
include::{dromblersourcedir}/org/drombler/acp/core/standard/action/impl/SaveAction.java[lines=28..31]
----

*Save All*:

[source,java]
----
include::{dromblersourcedir}/org/drombler/acp/core/standard/action/impl/SaveAllAction.java[lines=32..35]
----

The "Save" action looks for an instance of the interface org.drombler.acp.core.standard.action.Savable in the _active context_.

The "Save All" action looks for all instances of the same interface in the _application context_.

See <<context-framework.adoc#contextFramework,Context Framework>> for more information about the _Context Framework_.


*Exit*:

[source,java]
----
include::{dromblersourcedir}/org/drombler/fx/core/standard/action/impl/ExitAction.java[lines=30..32]
----

== Context Sensitive Actions

_Drombler FX_ checks if an Action implements org.drombler.commons.context.ActiveContextSensitive or org.drombler.commons.context.ApplicationContextSensitive and injects the active/ application-wide context.

See <<context-framework.adoc#contextFramework,Context Framework>> for more information about the Context Framework.

== Samples

In this section you will find some annotated Action samples.

=== Basic Sample
The following sample shows a simple action implementation, which is registered as a menu item in the menu with the ID "File" and as a toolbar button in the toolbar with the ID "file".

[source,java]
----
include::{sourcedir}/tutorial/action/sample/impl/MyAction1.java[lines=15..33]
----

=== Active Context Sensitive Sample
The following sample shows a active context sensitive action implementation. It looks for a MyCommand instance in the active context and listens for changes of the active context. If it finds a MyCommand instance, the Action gets enabled, else it gets disabled. If the Action gets triggered (onAction-method), then a method of MyCommand gets called.

[source,java]
----
include::{sourcedir}/tutorial/action/sample/impl/MyAction2.java[lines=15..55]
----

=== Application Context Sensitive Sample
The following sample shows a application context sensitive action implementation. It looks for all MyCommand instances in the application-wide context and listens for changes of this context. If it finds any MyCommand instance, the Action gets enabled, else it gets disabled. If the Action gets triggered (onAction-method), then a method of MyCommand gets called on all found instances.

[source,java]
----
include::{sourcedir}/tutorial/action/sample/impl/MyAction3.java[lines=15..59]
----

=== Basic Toggle Sample

The following sample shows a simple toggle action implementation, which is registered as a toggle menu item in the menu with the ID "File" and as a toolbar toggle button in the toolbar with the ID "file". Both the menu item and the toolbar button participate in a toggle group.

[source,java]
----
include::{sourcedir}/tutorial/action/sample/impl/MyToggleAction.java[lines=15..32]
----

=== More Samples

To see more samples have a look at the Sample Application described in the <<getting-started.adoc#gettingStarted,Getting Started>> section.