[[extensions]]
= Extensions
:toc:
:numbered:
:icons: font

The OSGi service layer in general and the OSGi Declarative Services in particular already make it quite easy to decouple bundles.

Especially if you want to associate some meta data declaratively you will hit a limit with Declarative Services.

https://enroute.osgi.org/FAQ/400-patterns.html#extender-pattern[Extender Pattern] (?)...

_Drombler FX_ uses the concept of _extension points_ and _extensions_.

_Extension points_, provided by _Drombler FX_ itself or by some framework developers, allow other developers to register extensions
to extend the application, e.g. adding some GUI elements declaratively.

Most _Drombler FX_ developers will register extensions of existing extension points rather than defining their own custom extension points.

== Predefined Extension Points by Drombler FX
_Drombler FX_ provides several extension points out-of-the-box:

 * actions, menu entries, menus, toolbar entries, toolbars - see <<actions-menus-toolbars.adoc#actionsMenusToolbars,Actions, Menus and Toolbars>> for more information
 * document data handlers, business object data handlers, file extensions - see <<data-framework.adoc#dataFramework,Data Framework>> for more information
 * views, editors - see <<docking-framework.adoc#dockingFramework,Docking Framework>> for more information
 * status bar entries - see <<status-bar.adoc#statusBar,Status Bar>> for more information

== Register an Extension for an Extension Point
Extensions are registered in _/META-INF/drombler/application.xml_.

There are several ways to register an extension based on an extension point.

=== Extension Annotations
The easiest way to register an extension is usually to use the extension point specific annotations.

If the annotation processor was registered correctly alongside with the annotations then you just need to declare the corresponding dependency and 
add the annotations to a supported target.

The compiler will pick up the annotation processor and write the application.xml once all annotations of all extension points in a bundle are processed.

[source,java]
----
include::{sourcedir}/tutorial/extension/foo/impl/FooComponent1.java[lines=5..6]
----

=== Extension File
Another way to register an extension is to provide an extension point specific XML file.

This is approach can also be use when the extension point provider didn't specify any extension point specific annotation.

[source,xml]
----
include::{resourcesdir}/META-INF/drombler/foos.xml[lines=1..9]
----

You can register this extension file using the 
http://www.drombler.org/drombler-acp/{drombler-acp-version}/docs/site/apidocs/org/drombler/acp/core/application/Extension.html[@Extension] annotation on a package (usually in 
_package-info.java_):

[source,java]
----
include::{sourcedir}/tutorial/extension/foo/package-info.java[lines=1..6]
----

=== application.xml
You can also just provide the whole _application.xml_ file at the correct location (_/META-INF/drombler/application.xml_).

[source,xml]
----
include::{resourcesdir}/META-INF/drombler/application.xml[lines=1..14]
----


=== Programmatic
_Drombler FX_ registers each unmarshalled extension JAXB object as an OSGi service.

You can do this also programmatically.

[source,java]
----
include::{sourcedir}/tutorial/extension/foo/ProgrammaticFooRegistrar.java[lines=10..28]
----

[source,java]
----
include::{sourcedir}/tutorial/extension/foo/ProgrammaticFooRegistrar.java[lines=30..34]
----


== Custom Extension Points
Every extension point has to register a custom org.drombler.acp.core.application.ExtensionPoint implementation as an OSGi service.

The only method you have to implement is to provide to JAXB class for the root element.

[source,java]
----
include::{sourcedir}/tutorial/extension/foo/impl/FooExtensionPoint.java[lines=3..15]
----
=== Handlers
Once you defined your extension point you usually need a handler service which does something with the extension.

When Drombler FX reads the application.xml it will register each unmarshalled root element as an OSGi service.

This allows OSGi services to listen for new instances.

[source,java]
----
include::{sourcedir}/tutorial/extension/foo/impl/FooHandler.java[lines=41..48]
----

=== Annotations (optional)
If you want to provide some convenience for the developers who want to use your extension point, consider to provide a custom annotation.
Though this highly recommended, this is an optional step and not required.

[source,java]
----
include::{sourcedir}/tutorial/extension/foo/Foo.java[lines=9..17]
----

==== Annotation Processor (optional)
If you define a custom annotation for your extension point you also need to provide an annotation processor, which adds the extension configuration to
the application.xml file.

[source,java]
----
include::{sourcedir}/tutorial/extension/foo/impl/FooAnnotationProcessor.java[lines=1..53]
----

[source,xml]
----
include::{resourcesdir}/META-INF/services/javax.annotation.processing.Processor[lines=1..1]
----

[source,java]
----
<java.compiler.compilerArgument>-proc:none</java.compiler.compilerArgument>
----

===== Tips & Tricks


[source,java]
----
include::{sourcedir}/tutorial/extension/some/impl/SomeComponent.java[lines=6..7]
----
https://www.softsmithy.org/softsmithy-lib/lib/{softsmithy-version}/docs/site/apidocs/org/softsmithy/lib/lang/model/type/ModelTypeUtils.html#getTypeMirror-java.util.function.Supplier-[ModelTypeUtils.getTypeMirror]

[source,java]
----
include::{sourcedir}/tutorial/extension/some/impl/SomeAnnotationProcessor.java[lines=21..29]
----


[source,java]
----
include::{sourcedir}/tutorial/extension/other/impl/SomeOtherComponent.java[lines=7..8]
----
https://www.softsmithy.org/softsmithy-lib/lib/{softsmithy-version}/docs/site/apidocs/org/softsmithy/lib/lang/model/element/ModelTypeUtils.html#getTypeMirrorsOfClassArrayAnnotationValue-java.util.List-java.lang.Class-java.lang.String-[ModelTypeUtils.getTypeMirrorsOfClassArrayAnnotationValue]

[source,java]
----
include::{sourcedir}/tutorial/extension/other/impl/SomeOtherAnnotationProcessor.java[lines=24..36]
----

[source,java]
----
["tutorial.extension.other.package1.Bar1", "tutorial.extension.other.package2.Bar2"]
----

=== Descriptors (optional)




