[[tutorial]]
= Drombler FX
Florian Brunner <fbrunnerreg@gmx.ch>
:description: The modular application framework for JavaFX.
:keywords: Application Framework, Drombler FX, Java, JavaFX, Maven, OSGi, RCP
:revnumber: {project-version}
:toc:

The modular application framework for _JavaFX_ based on:

    * *OSGi*: _OSGi_ is the de facto standard for writing modular software in _Java_.
    * *Maven (POM-first)*: _Drombler FX_ applications can be build with _Maven_. 
                       The build follows the standard POM-first approach (the OSGi meta data will be generated for you).
                       A custom Maven Plugin will help you to easily create _JavaFX_ applications with Maven. 
                       A custom Maven Archetype will help you to get started.
    * *Declarative programming model*: Annotations can be used at many places to register elements such as menus, toolbars and GUI components.
    * *Drombler ACP*: _Drombler FX_ is a _JavaFX_ specific extension for _Drombler ACP_ providing 
                      _JavaFX_-based implementations for the abstract definitions. 
                      Read more about _Drombler ACP_ here: http://www.drombler.org/drombler-acp[Drombler ACP]
    * *Drombler Commons*: _Drombler Commons_ is a collection of reusable libraries and frameworks. 
                          They ship with _OSGi_ meta data but don't require an _OSGi_ environment. Read more about _Drombler Commons_ here: http://www.drombler.org/drombler-commons[Drombler Commons]

_Drombler FX_ uses http://felix.apache.org[Apache Felix] as its OSGi container by default.

As an application framework it makes sure _JavaFX_ and _OSGi_ will get started properly and it provides the main window.

== Where to go from here

 * <<getting-started.adoc#gettingStarted,Getting Started>>
 * <<actions-menus-toolbars.adoc#actionsMenusToolbars,Actions, Menus and Toolbars>>
 * <<docking-framework.adoc#dockingFramework,Docking Framework>>
 * <<data-framework.adoc#dataFramework,Data Framework>>
 * <<context-framework.adoc#contextFramework,Context Framework>>
 * <<data-framework.adoc#dataFramework,Data Framework>>
 * <<localization.adoc#localization,Localization>>
 * <<logging.adoc#logging,Logging>>
 * <<ide.adoc#ide,IDEs>>
 * <<single-instance-application.adoc#singleInstanceApplication,Single Instance Application>>





