[[statusBar]]
= Status Bar
:toc:
:numbered:

This section describes an initial version of a modular _Status Bar Framework_.

[[activation]]
== Activation
To enable the _Status Bar Framework_ you need an _OSGi_ service which provides an implementation of
http://www.drombler.org/drombler-acp/{drombler-acp-version}/docs/site/apidocs/org/drombler/acp/core/status/spi/StatusBarElementContainerProvider.html[StatusBarElementContainerProvider].

If you're using the <<application-layout.adoc#standardDesktopClassicLayout,Standard Desktop Classic Layout>> an implementation based on 
http://www.drombler.org/drombler-commons/{drombler-commons-version}/docs/site/apidocs/org/drombler/commons/fx/scene/control/StatusBar.html[StatusBar] 
will be provided out-of-the-box.


== Status Bar Element Registration
To register a subclass of http://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html[Node] as a status bar element, just annotate it with 
http://www.drombler.org/drombler-acp/{drombler-acp-version}/docs/site/apidocs/org/drombler/acp/core/status/StatusBarElement.html[StatusBarElement]:

[source,java]
----
include::{sourcedir}/tutorial/statusbar/SampleStatusBarElement.java[lines=21..22]
----

The status bar elements are sorted per 
http://www.drombler.org/drombler-commons/{drombler-commons-version}/docs/site/apidocs/org/drombler/commons/client/geometry/HorizontalAlignment.html[HorizontalAlignment] according to 
their positions.

Please note that it's a best practice to leave some space between positions so that other modules have a chance to register other status bar elements where they like to.

If two adjacent status bar elements are positioned in different thousand groups (e.g. `position = 910` and `position = 1120`), a 
http://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Separator.html[Separator] gets automatically registered between them.

== Context Sensitive Implementations

Most status bar elements will likely want to reflect some state in the application.
You can use the <<context-framework.adoc#contextFramework,Context Framework>> e.g. to listen for objects in the <<context-framework.adoc#activeContext,active>> or in the 
<<context-framework.adoc#applicationContext,application-wide>> context.

The _Context Framework_ allows you to design your modules in a loosely-coupled way.

== Standard Status Bar Elements
Drombler FX provides some standard status bar elements out-of-the-box.

=== Progress Monitor Status Bar Element
Drombler FX provides a _Progress Monitor Status Bar Element_ out of the box.
Please see <<progress-monitor.adoc#activation,Progress Monitor Activation>> for more information about how to activate this module.